language: python

sudo: required
dist: trusty

python:
  - 2.7

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq swig openbabel python-openbabel
  - export PYTHONPATH=/usr/lib/python2.7/dist-packages:$PYTHONPATH

script:
  - python -m pytest test_molecule.py
